#Resource Icon, 1, "time_delete.ico"

#Resource VersionInfo
#Resource FileVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0
#Resource ProductVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0

#Resource StringInfo "0407", "04B0"

#Resource Version$ "CompanyName",      "BasicAware"
#Resource Version$ "FileDescription",  "Delete old files"
#Resource Version$ "LegalCopyright",   "Copyright 2013-2016 BasicAware"
#Resource Version$ "OriginalFilename", "DeleteFilesOlderThan.exe"
#Resource Version$ "ProductName",      "DeleteFilesOlderThan"
#Resource Version$ "ProductVersion",   "1.4.2.0"
#Resource Version$ "FileVersion",      "1.4.2.0"
#Resource Version$ "Comments",         "Written by Knuth Konrad"

$COMPANY_NAME = "BasicAware"
